import type {
  PersonalColor,
  ProductArea,
  ProductCategory,
  SkinConcern,
  SkinCondition,
  SkinType,
} from "./types";

export type CatalogProduct = {
  id: string;
  name: string;
  brand: string;
  price: number;
  category: ProductCategory;
  area: ProductArea;
  skinTypes: SkinType[];
  skinConditions: SkinCondition[];
  concerns: SkinConcern[];
  personalColors: PersonalColor[];
  ageMin?: number;
  ageMax?: number;
  description: string;
  reasonTemplate: string;
  tags: string[];
};

export const SKIN_TYPES: SkinType[] = ["乾燥肌", "脂性肌", "混合肌", "敏感肌"];
export const SKIN_CONDITIONS: SkinCondition[] = ["赤み", "くすみ", "黄ぐすみ", "毛穴"];
export const SKIN_CONCERNS: SkinConcern[] = ["しわ", "ニキビ", "しみ", "美白", "保湿", "毛穴"];
export const PERSONAL_COLORS: PersonalColor[] = [
  "イエベ春",
  "イエベ秋",
  "ブルベ夏",
  "ブルベ冬",
];

export const PRODUCT_CATALOG: CatalogProduct[] = [
  {
    id: "sk_01",
    name: "オイルクレンジング",
    brand: "DHC",
    price: 1980,
    category: "クレンジング",
    area: "skincare",
    skinTypes: ["乾燥肌", "混合肌"],
    skinConditions: [],
    concerns: ["保湿"],
    personalColors: [],
    description: "オリーブ由来。メイクも毛穴汚れもやさしく落とす定番。",
    reasonTemplate: "乾燥しやすい肌でもつっぱらず、メイクオフがしっかりできます。",
    tags: ["ベストセラー"],
  },
  {
    id: "sk_02",
    name: "マイルドクレンジング",
    brand: "資生堂",
    price: 1650,
    category: "クレンジング",
    area: "skincare",
    skinTypes: ["脂性肌", "混合肌", "敏感肌"],
    skinConditions: ["赤み"],
    concerns: ["ニキビ"],
    personalColors: [],
    description: "さっぱり洗い上がり。敏感肌・ニキビ肌向け。",
    reasonTemplate: "脂性肌・ニキビ悩みには、負担の少ないクレンジングが第一歩です。",
    tags: ["ニキビ肌向け"],
  },
  {
    id: "sk_03",
    name: "泡洗顔",
    brand: "専科",
    price: 880,
    category: "洗顔",
    area: "skincare",
    skinTypes: ["脂性肌", "混合肌"],
    skinConditions: ["毛穴"],
    concerns: ["毛穴", "ニキビ"],
    personalColors: [],
    description: "もっちり泡で皮脂と汚れをオフ。",
    reasonTemplate: "毛穴・皮脂ケアには、泡でやさしく洗う洗顔がおすすめです。",
    tags: ["コスパ◎"],
  },
  {
    id: "sk_04",
    name: "クリーム洗顔",
    brand: "Curel",
    price: 1320,
    category: "洗顔",
    area: "skincare",
    skinTypes: ["乾燥肌", "敏感肌"],
    skinConditions: ["赤み"],
    concerns: ["保湿"],
    personalColors: [],
    description: "セラミド配合。摩擦を抑えた洗顔。",
    reasonTemplate: "乾燥肌・赤みには、保湿を守るクリーム系洗顔が合います。",
    tags: ["敏感肌"],
  },
  {
    id: "sk_05",
    name: "保湿化粧水",
    brand: "無印良品",
    price: 990,
    category: "化粧水",
    area: "skincare",
    skinTypes: ["乾燥肌", "混合肌", "敏感肌"],
    skinConditions: ["くすみ"],
    concerns: ["保湿", "美白"],
    personalColors: [],
    description: "シンプル保湿。敏感肌でも使いやすい。",
    reasonTemplate: "肌の土台づくりに、刺激の少ない保湿化粧水を。",
    tags: ["敏感肌OK"],
  },
  {
    id: "sk_06",
    name: "薬用美白化粧水",
    brand: "HAKU",
    price: 5500,
    category: "化粧水",
    area: "skincare",
    skinTypes: ["混合肌", "乾燥肌"],
    skinConditions: ["くすみ", "黄ぐすみ"],
    concerns: ["しみ", "美白"],
    personalColors: [],
    ageMin: 20,
    description: "トラネキサム酸配合。透明感ケア。",
    reasonTemplate: "しみ・くすみが気になる方には、美白有効成分入り化粧水が効果的です。",
    tags: ["美白"],
  },
  {
    id: "sk_07",
    name: "ニキビケア化粧水",
    brand: "オルビス",
    price: 1980,
    category: "化粧水",
    area: "skincare",
    skinTypes: ["脂性肌", "混合肌"],
    skinConditions: ["赤み", "毛穴"],
    concerns: ["ニキビ", "毛穴"],
    personalColors: [],
    description: "さっぱり使用感。ニキビ予防に。",
    reasonTemplate: "脂性肌・ニキビには、べたつかない化粧水で油分バランスを整えましょう。",
    tags: ["ニキビ"],
  },
  {
    id: "sk_08",
    name: "レチノール美容液",
    brand: "資生堂",
    price: 8800,
    category: "美容液",
    area: "skincare",
    skinTypes: ["乾燥肌", "混合肌"],
    skinConditions: ["くすみ"],
    concerns: ["しわ", "美白"],
    personalColors: [],
    ageMin: 25,
    description: "ハリ・ツヤ・シワ改善をサポート。",
    reasonTemplate: "年齢に応じたエイジングケアとして、レチノール美容液がおすすめです。",
    tags: ["エイジング"],
  },
  {
    id: "sk_09",
    name: "ビタミンC美容液",
    brand: "TAKAMI",
    price: 5500,
    category: "美容液",
    area: "skincare",
    skinTypes: ["脂性肌", "混合肌", "乾燥肌"],
    skinConditions: ["くすみ", "毛穴"],
    concerns: ["しみ", "美白", "毛穴"],
    personalColors: [],
    description: "角質ケア＋透明感。毛穴も引き締め。",
    reasonTemplate: "しみ・毛穴・くすみをまとめてケアしたい方に。",
    tags: ["透明感"],
  },
  {
    id: "sk_10",
    name: "セラミド乳液",
    brand: "Curel",
    price: 2200,
    category: "乳液",
    area: "skincare",
    skinTypes: ["乾燥肌", "敏感肌"],
    skinConditions: ["赤み"],
    concerns: ["保湿", "しわ"],
    personalColors: [],
    description: "乾燥小ジワを目立たなくする乳液。",
    reasonTemplate: "乾燥による小ジワ予防には、セラミド乳液で保湿をキープ。",
    tags: ["保湿"],
  },
  {
    id: "sk_11",
    name: "オールインワンゲル",
    brand: "ちふれ",
    price: 880,
    category: "クリーム",
    area: "skincare",
    skinTypes: ["混合肌", "脂性肌"],
    skinConditions: [],
    concerns: ["保湿"],
    personalColors: [],
    description: "化粧水・乳液・クリームがこれ1つ。",
    reasonTemplate: "予算を抑えつつ保湿したい方に、コスパの良いオールインワン。",
    tags: ["コスパ◎"],
  },
  {
    id: "sk_12",
    name: "UV乳液 SPF50+",
    brand: "アネッサ",
    price: 3300,
    category: "日焼け止め",
    area: "skincare",
    skinTypes: ["乾燥肌", "脂性肌", "混合肌", "敏感肌"],
    skinConditions: [],
    concerns: ["しみ", "美白", "しわ"],
    personalColors: [],
    description: "紫外線対策の定番。シミ・シワ予防の基本。",
    reasonTemplate: "美白・しみ・しわ対策には、毎日のUVケアが必須です。",
    tags: ["必須"],
  },
  {
    id: "mk_01",
    name: "リキッドファンデ",
    brand: "SUQQU",
    price: 8800,
    category: "ファンデ",
    area: "makeup",
    skinTypes: ["乾燥肌", "混合肌"],
    skinConditions: ["くすみ"],
    concerns: ["保湿"],
    personalColors: ["イエベ春", "イエベ秋", "ブルベ夏", "ブルベ冬"],
    description: "自然なツヤ肌。色選びで肌トーン補正。",
    reasonTemplate: "パーソナルカラーに合わせた色味で、肌の赤みやくすみを自然にカバー。",
    tags: ["ツヤ肌"],
  },
  {
    id: "mk_02",
    name: "パウダーファンデ",
    brand: "CANMAKE",
    price: 1320,
    category: "ファンデ",
    area: "makeup",
    skinTypes: ["脂性肌", "混合肌"],
    skinConditions: ["毛穴", "赤み"],
    concerns: ["ニキビ", "毛穴"],
    personalColors: ["イエベ春", "ブルベ夏"],
    description: "毛穴カバー◎。テカリ防止。",
    reasonTemplate: "脂性肌・毛穴が気になる方には、さらさらパウダー系が合います。",
    tags: ["毛穴カバー"],
  },
  {
    id: "mk_03",
    name: "カラーコレクティングコンシーラー",
    brand: "IPSA",
    price: 4400,
    category: "コンシーラー",
    area: "makeup",
    skinTypes: ["混合肌", "乾燥肌", "脂性肌"],
    skinConditions: ["赤み", "くすみ"],
    concerns: ["ニキビ", "しみ"],
    personalColors: [],
    description: "3色使い分け。赤み・くすみ・シミを部分カバー。",
    reasonTemplate: "赤みやニキビ跡は、グリーン・オレンジ系で部分補正が効果的です。",
    tags: ["部分使い"],
  },
  {
    id: "mk_04",
    name: "チーク",
    brand: "CEZANNE",
    price: 550,
    category: "チーク",
    area: "makeup",
    skinTypes: [],
    skinConditions: [],
    concerns: [],
    personalColors: ["イエベ春", "イエベ秋"],
    description: "コーラル・ピーチ系。イエベ向け。",
    reasonTemplate: "イエベの方には、温かみのあるコーラル系チークが血色感アップ。",
    tags: ["イエベ"],
  },
  {
    id: "mk_05",
    name: "チーク",
    brand: "CANMAKE",
    price: 880,
    category: "チーク",
    area: "makeup",
    skinTypes: [],
    skinConditions: [],
    concerns: [],
    personalColors: ["ブルベ夏", "ブルベ冬"],
    description: "ローズ・ラベンダー系。ブルベ向け。",
    reasonTemplate: "ブルベの方には、青みのあるローズ系が透明感を出します。",
    tags: ["ブルベ"],
  },
  {
    id: "mk_06",
    name: "アイシャドウパレット",
    brand: "LUNASOL",
    price: 5500,
    category: "アイメイク",
    area: "makeup",
    skinTypes: [],
    skinConditions: [],
    concerns: [],
    personalColors: ["イエベ春", "イエベ秋", "ブルベ夏", "ブルベ冬"],
    description: "4色パレット。目元の印象を整える。",
    reasonTemplate: "パーソナルカラーに合ったアイシャドウで、顔全体のバランスが整います。",
    tags: ["目元"],
  },
  {
    id: "mk_07",
    name: "マスカラ",
    brand: "ヒロインメイク",
    price: 990,
    category: "アイメイク",
    area: "makeup",
    skinTypes: [],
    skinConditions: [],
    concerns: [],
    personalColors: [],
    description: "ロング＆カール。にじみにくい。",
    reasonTemplate: "目元の印象を引き上げる、コスパの良いマスカラ。",
    tags: ["定番"],
  },
  {
    id: "mk_08",
    name: "ティントリップ",
    brand: "rom&nd",
    price: 1320,
    category: "リップ",
    area: "makeup",
    skinTypes: [],
    skinConditions: [],
    concerns: [],
    personalColors: ["イエベ春", "イエベ秋"],
    description: "オレンジ・コーラル系。イエベ向け。",
    reasonTemplate: "イエベの方には、オレンジ・コーラル系リップが似合います。",
    tags: ["イエベ"],
  },
  {
    id: "mk_09",
    name: "ティントリップ",
    brand: "rom&nd",
    price: 1320,
    category: "リップ",
    area: "makeup",
    skinTypes: [],
    skinConditions: [],
    concerns: [],
    personalColors: ["ブルベ夏", "ブルベ冬"],
    description: "ローズ・プラム系。ブルベ向け。",
    reasonTemplate: "ブルベの方には、青みピンク・ローズ系リップがおすすめ。",
    tags: ["ブルベ"],
  },
  {
    id: "fa_01",
    name: "コットンシャツ",
    brand: "UNIQLO",
    price: 2990,
    category: "トップス",
    area: "fashion",
    skinTypes: [],
    skinConditions: [],
    concerns: [],
    personalColors: ["イエベ春", "ブルベ夏"],
    description: "白・淡色。清潔感のあるベーシック。",
    reasonTemplate: "清楚系・ナチュラルな印象には、白や淡色のシャツが万能。",
    tags: ["ベーシック"],
  },
  {
    id: "fa_02",
    name: "ニットプルオーバー",
    brand: "GU",
    price: 1990,
    category: "トップス",
    area: "fashion",
    skinTypes: [],
    skinConditions: [],
    concerns: [],
    personalColors: ["イエベ秋", "ブルベ冬"],
    description: "ベージュ・モカ・ネイビー。秋冬向け。",
    reasonTemplate: "深みのある色味は、秋・冬タイプのパーソナルカラーと相性◎。",
    tags: ["秋冬"],
  },
  {
    id: "fa_03",
    name: "ハイウエストパンツ",
    brand: "ZARA",
    price: 5990,
    category: "ボトムス",
    area: "fashion",
    skinTypes: [],
    skinConditions: [],
    concerns: [],
    personalColors: [],
    description: "脚長効果。きれいめコーデの定番。",
    reasonTemplate: "スタイルアップしたい方に、ハイウエストパンツでバランスを整えましょう。",
    tags: ["脚長"],
  },
  {
    id: "fa_04",
    name: "プリーツスカート",
    brand: "LOWRYS FARM",
    price: 4990,
    category: "ボトムス",
    area: "fashion",
    skinTypes: [],
    skinConditions: [],
    concerns: [],
    personalColors: ["イエベ春", "ブルベ夏"],
    description: "フェミニンなシルエット。",
    reasonTemplate: "柔らかい印象を出したい方に、プリーツスカートがおすすめ。",
    tags: ["フェミニン"],
  },
  {
    id: "fa_05",
    name: "テーラードジャケット",
    brand: "UNIQLO",
    price: 7990,
    category: "アウター",
    area: "fashion",
    skinTypes: [],
    skinConditions: [],
    concerns: [],
    personalColors: ["ブルベ冬", "イエベ秋"],
    ageMin: 20,
    description: "きちんと感。ON/OFF使える。",
    reasonTemplate: "大人っぽい印象に整えたい方に、ジャケットで全体の完成度を上げましょう。",
    tags: ["きれいめ"],
  },
  {
    id: "fa_06",
    name: "ダウンジャケット",
    brand: "UNIQLO",
    price: 9990,
    category: "アウター",
    area: "fashion",
    skinTypes: [],
    skinConditions: [],
    concerns: [],
    personalColors: [],
    description: "軽くて暖かい。カジュアルコーデ向け。",
    reasonTemplate: "日常使いしやすいアウターとして、軽量ダウンが活躍します。",
    tags: ["カジュアル"],
  },
  {
    id: "fa_07",
    name: "パールピアス",
    brand: "アクセサリーショップ",
    price: 1980,
    category: "アクセサリー",
    area: "fashion",
    skinTypes: [],
    skinConditions: [],
    concerns: [],
    personalColors: ["イエベ春", "ブルベ夏", "ブルベ冬"],
    description: "顔周りを明るく。清楚・上品に。",
    reasonTemplate: "顔周りに光を足して、肌のトーンを明るく見せる小物です。",
    tags: ["小顔効果"],
  },
  {
    id: "fa_08",
    name: "ゴールドネックレス",
    brand: "アクセサリーショップ",
    price: 2980,
    category: "アクセサリー",
    area: "fashion",
    skinTypes: [],
    skinConditions: [],
    concerns: [],
    personalColors: ["イエベ春", "イエベ秋"],
    description: "イエベ向け。温かみのあるゴールド。",
    reasonTemplate: "イエベの方には、ゴールド系アクセが肌と相性良く映えます。",
    tags: ["イエベ"],
  },
  {
    id: "fa_09",
    name: "シルバーネックレス",
    brand: "アクセサリーショップ",
    price: 2980,
    category: "アクセサリー",
    area: "fashion",
    skinTypes: [],
    skinConditions: [],
    concerns: [],
    personalColors: ["ブルベ夏", "ブルベ冬"],
    description: "ブルベ向け。クールなシルバー。",
    reasonTemplate: "ブルベの方には、シルバー系アクセが透明感を引き立てます。",
    tags: ["ブルベ"],
  },
];

export const CATEGORY_ORDER: Record<ProductArea, ProductCategory[]> = {
  skincare: ["クレンジング", "洗顔", "化粧水", "美容液", "乳液", "クリーム", "日焼け止め"],
  makeup: ["ファンデ", "コンシーラー", "チーク", "アイメイク", "リップ"],
  fashion: ["トップス", "ボトムス", "アウター", "アクセサリー"],
};
